### ISSUE TITLE
Incompatible with EAP?

### ISSUE THREAD

**Issue by cpriest** [halirutan/IntelliJ-Key-Promoter-X#16]
I loved this re-write, thank you.  It's been non-functional for some time now, it simply says 'Plugin is incompatible with current PhpStorm installation' which is the current EAP for me:

```
PhpStorm 2018.1 EAP
Build #PS-181.3870.19, built on February 21, 2018
PhpStorm EAP User
Expiration date: March 23, 2018
JRE: 1.8.0_152-release-1136-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by halirutan** [comment]
Works for me with the same PHPStorm version. Please ensure that you have the version 5.11 of the Key Promoter X.

**Comment by cpriest** [comment]
I'll check it out again, perhaps uninstall/reinstall.

**Comment by cpriest** [comment]
Okay, so did need to update to 5.11, but now I get the following on startup of PhpStorm:

```
Plugin 'Key Promoter X' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.AssertionError
    at com.intellij.util.xmlb.MapBinding.deserializeKeyOrValue(MapBinding.java:233)
    at com.intellij.util.xmlb.MapBinding.deserialize(MapBinding.java:190)
    at com.intellij.util.xmlb.MapBinding.deserializeList(MapBinding.java:142)
    at com.intellij.util.xmlb.Binding.deserializeList(Binding.java:41)
    at com.intellij.util.xmlb.OptionTagBinding.deserialize(OptionTagBinding.java:94)
    at com.intellij.util.xmlb.BasePrimitiveBinding.deserializeUnsafe(BasePrimitiveBinding.java:54)
    at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:216)
    at com.intellij.util.xmlb.BeanBinding.deserializeInto(BeanBinding.java:170)
    at com.intellij.configurationStore.KotlinAwareBeanBinding.deserialize(xmlSerializer.kt:189)
    at com.intellij.configurationStore.XmlSerializer.deserialize(xmlSerializer.kt:75)
    at com.intellij.configurationStore.DefaultStateSerializerKt.deserializeState(DefaultStateSerializer.kt:40)
    at com.intellij.configurationStore.StateStorageBase.deserializeState(StateStorageBase.kt:28)
    at com.intellij.configurationStore.StateGetterImpl.getState(StorageBaseEx.kt:68)
    at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:362)
    at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:331)
    at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:121)
    at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:96)
    at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.initializeComponent(PlatformComponentManagerImpl.java:54)
    at com.intellij.openapi.components.impl.ServiceManagerImpl$MyComponentAdapter.getComponentInstance(ServiceManagerImpl.java:225)
    at com.intellij.util.pico.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:240)
    at com.intellij.util.pico.DefaultPicoContainer.getComponentInstance(DefaultPicoContainer.java:207)
    at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:49)
    at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:39)
    at de.halirutan.keypromoterx.KeyPromoter.<init>(KeyPromoter.java:45)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:459)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:106)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:437)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:444)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:90)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:396)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:382)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:195)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:71)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:407)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by halirutan** [comment]
@cpriest Please see here https://github.com/halirutan/IntelliJ-Key-Promoter-X/issues/5#issuecomment-321979777

**Comment by cpriest** [comment]
Sure, I assume you mean you'd like to see that file on my end?  I can post it here
[KeyPromoterXStatistic.zip](https://github.com/halirutan/IntelliJ-Key-Promoter-X/files/1756475/KeyPromoterXStatistic.zip)

**Comment by halirutan** [comment]
@cpriest No, you need to delete it. If you are coming from an older version of Key Promoter X, the file format changed and this is why IDEA has a problem now. Close IDEA and delete this file. You statistic will be gone, but this will only be necessary one time as I have fixed the bug already.

**Comment by cpriest** [comment]
I see, I'll do that then, thank you.

**Comment by cpriest** [comment]
Just to follow up on this, that did take care of it, thanks!
