### ISSUE TITLE
NPE in KeyPromoterStatistics.registerAction(KeyPromoterStatistics.java:84)

### ISSUE THREAD

**Issue by dlsniper** [halirutan/IntelliJ-Key-Promoter-X#19]
Hi, 

Thank you for this awesome project.

Unfortunately, I have the following exception in GoLand 2018.1.5:

```
null
java.lang.NullPointerException
	at de.halirutan.keypromoterx.statistic.KeyPromoterStatistics.registerAction(KeyPromoterStatistics.java:84)
	at de.halirutan.keypromoterx.KeyPromoter.showTip(KeyPromoter.java:133)
	at de.halirutan.keypromoterx.KeyPromoter.beforeActionPerformed(KeyPromoter.java:120)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.fireBeforeActionPerformed(ActionManagerImpl.java:1208)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:152)
```

**Comment by halirutan** [comment]
I will try this out. I know where the NPE is coming from and obviously I'm using the `PropertyChangeSupport` API wrong although it worked. I'm not sure it's a recent change the invalidates my usage or if it is specific to GoLand.

In the mean-time, can you provide some details? If I'm right and the messaging doesn't work how I use it, then it should always throw the NPE. Does it work at all? When do you get the NPE?

**Comment by halirutan** [comment]
I tested it locally with GoLand with the same version you have and I cannot reproduce this. I definitely need some more details.

**Comment by dlsniper** [comment]
Hi, sorry for the delay. I cannot reproduce this either. Not sure what happened there, sorry :( If I manage to reproduce this, I'll let you know.

**Comment by halirutan** [comment]
No problem. If you encounter it again, collect as much information as possible. Thanks.
