### ISSUE TITLE
Add Webstorm 2021.2 support please

### ISSUE THREAD

**Issue by guchandeveloper** [halirutan/IntelliJ-Key-Promoter-X#81]
Add Webstorm 2021.2 support please.

**Comment by flexjoly** [comment]
and phpstorm 2021.2

**Comment by halirutan** [comment]
In progress. I need to clear up some final issues regarding deprecation but otherwise, it should be out very soon.

**Comment by halirutan** [comment]
Alright, I really need some people to test this before I release it. It will only work in 2021.2 versions because I got rid of all deprecated API usage. My main concern however is that I changed the way Key Promoter is instantiated to make if finally _dynamic_: It can be updated in the future without restarting the IDE.

Everyone who is willing to give it a shot, [please download the zip](https://github.com/halirutan/IntelliJ-Key-Promoter-X/releases/tag/untagged-77dc5c46676bd112d5be) and under **Settings | Plugins** use _install from disk_ you find under the settings wheel on the right side.

![image](https://user-images.githubusercontent.com/511683/123565848-7c0e4480-d7be-11eb-9575-c6cd49537fbd.png)

**Comment by flexjoly** [comment]
Hi @halirutan,

I would like to help and install the zip, but the link is not working. I also tried to find it in the tags, releases etc. 

Greet, flexjoly

**Comment by halirutan** [comment]
I didn't realize that only I can see the "draft releases". I'll attach the zip below. One thing I found is that with the new instantiation method the Key Promoter won't work until your press a "real" button. Luckily almost all buttons are real buttons but for instance, the tool-window buttons are not. I'm not sure I want to keep it that way..

[Key-Promoter-X-2021.2.zip](https://github.com/halirutan/IntelliJ-Key-Promoter-X/files/6743134/Key-Promoter-X-2021.2.zip)

**Comment by flexjoly** [comment]
I installed it about an hour ago. It works great, no problems so far.

![image](https://user-images.githubusercontent.com/8533733/124090251-f5bf6000-da54-11eb-8edb-8736b9256bb7.png)

**Comment by thecodemonk** [comment]
Installed it on the latest EAP for Rider. So far, working good.

**Comment by litong534** [comment]
it's working good, thank you

**Comment by amitranjan53** [comment]
> I didn't realize that only I can see the "draft releases". I'll attach the zip below. One thing I found is that with the new instantiation method the Key Promoter won't work until your press a "real" button. Luckily almost all buttons are real buttons but for instance, the tool-window buttons are not. I'm not sure I want to keep it that way..
> 
> [Key-Promoter-X-2021.2.zip](https://github.com/halirutan/IntelliJ-Key-Promoter-X/files/6743134/Key-Promoter-X-2021.2.zip)

I see what you mean. It indeed is not showing up for any tool window. But normal shortcuts are working fine.  Right now after upgrading the plugin itself is totally not working. May be publish the basics working. This itself is very useful till there is a patch.

**Comment by Kubik-Rubik** [comment]
@halirutan Thanks for the useful plugin!

Just installed the test package on the latest PhpStorm version 2021.2 and it works as expected. Please update the official release!

<img width="471" alt="grafik" src="https://user-images.githubusercontent.com/1976103/127561356-87c92532-63b8-421b-a333-e52fb2f3dfd3.png">

**Comment by michele-mangili** [comment]
I have been testing it with WebStorm an PyCharm and so far it is working great. Thank you!

**Comment by ComiR** [comment]
I'm using the draft version and just got the following exception about half an hour ago. Unfortunately I didn't notice it until now, so I can't tell you what triggered it.

<details>
<summary>Exception message</summary>

```
org.jetbrains.mvstore.MVStoreException: End of file /Users/comir/Library/Application Support/JetBrains/Toolbox/apps/PhpStorm/ch-0/212.4746.100/PhpStorm 2021.2 EAP.app/Contents/bin/icons.db (position=2968191, length null, read=0, remaining=49152)
	at org.jetbrains.mvstore.DataUtil.readFully(DataUtil.java:110)
	at org.jetbrains.mvstore.FileStore.readFully(FileStore.java:124)
	at org.jetbrains.mvstore.Chunk.readBufferForPage(Chunk.java:436)
	at org.jetbrains.mvstore.MVStore.doReadPage(MVStore.java:2630)
	at org.jetbrains.mvstore.MVStore.lambda$readPage$9(MVStore.java:2616)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$13(BoundedLocalCache.java:2439)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2437)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2420)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:104)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
	at org.jetbrains.mvstore.MVStore.readPage(MVStore.java:2616)
	at org.jetbrains.mvstore.NonLeafPage.getChildPage(NonLeafPage.java:62)
	at org.jetbrains.mvstore.Page.get(Page.java:205)
	at org.jetbrains.mvstore.MVMap.get(MVMap.java:372)
	at com.intellij.ui.svg.SvgPrebuiltCacheManager.loadFromCache(SvgPrebuiltCacheManager.java:48)
	at com.intellij.util.SVGLoader.loadFromClassResource(SVGLoader.java:144)
	at com.intellij.ui.RasterizedImageDataLoader.loadRasterized(RasterizedImageDataLoader.java:138)
	at com.intellij.ui.RasterizedImageDataLoader.loadImage(RasterizedImageDataLoader.java:55)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.loadImage(IconLoader.java:962)
	at com.intellij.openapi.util.IconLoader$ScaledIconCache.getOrScaleIcon(IconLoader.java:1031)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getRealIcon(IconLoader.java:850)
	at com.intellij.openapi.util.IconLoader$CachedImageIcon.getIconWidth(IconLoader.java:778)
	at java.desktop/javax.swing.plaf.basic.BasicLabelUI.getPreferredSize(BasicLabelUI.java:241)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1683)
	at com.intellij.notification.impl.NotificationsManagerImpl$CenteredLayoutWithActions.layoutContainer(NotificationsManagerImpl.java:1257)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/javax.swing.JLayeredPane.addImpl(JLayeredPane.java:238)
	at java.desktop/java.awt.Container.add(Container.java:436)
	at com.intellij.ui.BalloonImpl.createComponent(BalloonImpl.java:774)
	at com.intellij.ui.BalloonImpl.show(BalloonImpl.java:542)
	at com.intellij.ui.BalloonImpl.show(BalloonImpl.java:457)
	at com.intellij.ui.BalloonImpl.show(BalloonImpl.java:416)
	at com.intellij.ui.BalloonImpl.show(BalloonImpl.java:887)
	at com.intellij.ui.BalloonImpl.show(BalloonImpl.java:874)
	at com.intellij.ui.BalloonLayoutImpl.add(BalloonLayoutImpl.java:150)
	at com.intellij.notification.impl.NotificationsManagerImpl.notifyByBalloon(NotificationsManagerImpl.java:304)
	at com.intellij.notification.impl.NotificationsManagerImpl.showNotification(NotificationsManagerImpl.java:173)
	at com.intellij.notification.impl.NotificationsManagerImpl.lambda$doNotify$1(NotificationsManagerImpl.java:128)
	at com.intellij.util.ModalityUiUtil.invokeLaterIfNeeded(ModalityUiUtil.java:54)
	at com.intellij.notification.impl.NotificationsManagerImpl.doNotify(NotificationsManagerImpl.java:128)
	at com.intellij.notification.impl.NotificationsManagerImpl$MyNotificationListener.notify(NotificationsManagerImpl.java:1038)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy206.notify(Unknown Source)
	at com.intellij.notification.Notifications$Bus.doNotify(Notifications.java:85)
	at com.intellij.notification.Notifications$Bus.lambda$notify$1(Notifications.java:74)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:101)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2183)
	at com.intellij.notification.Notifications$Bus.notify(Notifications.java:74)
	at com.intellij.notification.Notification.notify(Notification.java:302)
	at de.halirutan.keypromoterx.KeyPromoterNotification.askToCreateShortcut(KeyPromoterNotification.java:69)
	at de.halirutan.keypromoterx.KeyPromoter.showTip(KeyPromoter.java:170)
	at de.halirutan.keypromoterx.KeyPromoter.beforeActionPerformed(KeyPromoter.java:135)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.access$300(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.executeOrAddToQueue(MessageBusImpl.java:208)
	at com.intellij.util.messages.impl.CompositeMessageBus$ToDirectChildrenMessagePublisher.publish(CompositeMessageBus.java:105)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:166)
	at com.sun.proxy.$Proxy161.beforeActionPerformed(Unknown Source)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.fireBeforeActionPerformed(ActionManagerImpl.java:1502)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:249)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:150)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:427)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:886)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:815)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
</details>
