### ISSUE TITLE
Clast Cast Exception in intelliJ

### ISSUE THREAD

**Issue by CarinaSchoppe** [halirutan/IntelliJ-Key-Promoter-X#95]
java.lang.ClassCastException: class com.jetbrains.rdserver.ui.popup.RdBalloon cannot be cast to class com.intellij.ui.BalloonImpl (com.jetbrains.rdserver.ui.popup.RdBalloon is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @1f5f99f; com.intellij.ui.BalloonImpl is in unnamed module of loader com.intellij.util.lang.PathClassLoader @629f0666)
	at com.intellij.ui.ActionCenterBalloonLayout$CollapseInfo.calculateSize(ActionCenterBalloonLayout.kt:296)
	at com.intellij.ui.ActionCenterBalloonLayout.calculateSize(ActionCenterBalloonLayout.kt:181)
	at com.intellij.ui.ActionCenterBalloonLayout.addNewBalloon(ActionCenterBalloonLayout.kt:85)
	at com.intellij.ui.ActionCenterBalloonLayout.doCollapse(ActionCenterBalloonLayout.kt:100)
	at com.intellij.ui.ActionCenterBalloonLayout.add(ActionCenterBalloonLayout.kt:58)
	at com.intellij.notification.impl.NotificationsManagerImpl.notifyByBalloon(NotificationsManagerImpl.java:330)
	at com.intellij.notification.impl.NotificationsManagerImpl.showNotification(NotificationsManagerImpl.java:195)
	at com.intellij.notification.impl.NotificationsManagerImpl.lambda$doNotify$1(NotificationsManagerImpl.java:146)
	at com.intellij.util.ModalityUiUtil.invokeLaterIfNeeded(ModalityUiUtil.java:56)
	at com.intellij.notification.impl.NotificationsManagerImpl.doNotify(NotificationsManagerImpl.java:145)
	at com.intellij.notification.impl.NotificationsManagerImpl$MyNotificationListener.notify(NotificationsManagerImpl.java:1156)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:625)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:399)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:368)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:437)
	at jdk.proxy1/jdk.proxy1.$Proxy219.setInfo(Unknown Source)
	at com.intellij.openapi.wm.StatusBar$Info.set(StatusBar.java:57)
	at com.intellij.notification.LogModel.setStatusMessage(LogModel.java:82)
	at com.intellij.notification.LogModel.setStatusMessage(LogModel.java:70)
	at com.intellij.notification.impl.ProjectNotificationModel$addNotification$1.run(NotificationsToolWindow.kt:1589)
	at com.intellij.notification.impl.ApplicationNotificationModel.addNotification(NotificationsToolWindow.kt:1490)
	at com.intellij.notification.impl.NotificationsToolWindowFactory$Companion.addNotification(NotificationsToolWindow.kt:77)
	at com.intellij.notification.impl.NotificationsToolWindowNotificationListener.notify(NotificationsToolWindowNotificationListener.java:26)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:649)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:625)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:399)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:378)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:437)
	at jdk.proxy1/jdk.proxy1.$Proxy218.notify(Unknown Source)
	at com.intellij.notification.Notifications$Bus.doNotify(Notifications.java:93)
	at com.intellij.notification.Notifications$Bus.lambda$notify$1(Notifications.java:79)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:113)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2100)
	at com.intellij.notification.Notifications$Bus.notify(Notifications.java:79)
	at com.intellij.notification.Notification.notify(Notification.java:396)
	at de.halirutan.keypromoterx.KeyPromoterNotification$ShowMode$1.showTip(KeyPromoterNotification.java:112)
	at de.halirutan.keypromoterx.KeyPromoterNotification.showTip(KeyPromoterNotification.java:52)
	at de.halirutan.keypromoterx.KeyPromoter.showTip(KeyPromoter.java:160)
	at de.halirutan.keypromoterx.KeyPromoter.handleMouseEvent(KeyPromoter.java:103)
	at de.halirutan.keypromoterx.KeyPromoter.eventDispatched(KeyPromoter.java:88)
	at java.desktop/java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2202)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2094)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2093)
	at java.desktop/java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2050)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4928)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by halirutan** [comment]
Hey Carina, can you give some details about the IDE you were using? Go to Help | About and press the Copy button.

This error looks weird because it seems to be a casting issue that has nothing to do with the Key Promoter X.

**Comment by CarinaSchoppe** [comment]
IntelliJ IDEA 2022.2 (Ultimate Edition)
Build #IU-222.3345.118, built on July 26, 2022
Licensed to Carina Sophie Schoppe
Subscription is active until February 12, 2023.
For educational use only.
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 3200M
Cores: 8
Registry:
    completion.show.intention.icon=false
    documentation.show.toolbar=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    some.awesome (1.14)
    net.seesharpsoft.intellij.plugins.csv (2.19.0)
    krasa.CpuUsageIndicator (1.14)
    com.wakatime.intellij.plugin (14.0.6)
    com.tabnine.TabNine (0.7.11)
    com.intellij.grazie.pro (0.3.107-221-222)
    com.github.copilot (1.1.28.1832-nightly)
    awesome.console (0.1337.12)
    Statistic (4.1.10)
    Key Promoter X (2022.2)
    org.sonarlint.idea (6.8.0.50884)
    mobi.hsz.idea.gitignore (4.4.2)
    com.mallowigi (65.1.0)
    com.almightyalpaca.intellij.plugins.discord (1.9.0)
    DBN (3.3.1923.0)
    com.intellij.plugins.html.instantEditing (222.3345.108)
    Pythonid (222.3345.131)
    io.snyk.snyk-intellij-plugin (2.4.40)
    MavenRunHelper (4.20.213.3714.1)
    zielu.gittoolbox (212.9.7)
    com.chrisrm.idea.MaterialThemeUI (7.7.1)
    izhangzhihao.rainbow.brackets (6.25)
    com.demonwav.minecraft-dev (2022.2-1.5.20-334)
    cn.yiiguxing.plugin.translate (3.3.4)
    AceJump (3.8.8)

Kotlin: 222-1.7.10-release-334-IJ3345.118

**Comment by halirutan** [comment]
The bad news is that it's indeed a bug in the [IntelliJ codebase](https://youtrack.jetbrains.com/issue/CWM-6516), the good news is that it has been fixed already and will be available in the next release.

Hold your breath for a little longer :)
